### ISSUE TITLE
Plex Debug message over and over

### ISSUE THREAD

**Issue by causefx** [scraton/node-red-contrib-plex-ws#3]
Hi, on one of my flows I get this message every 2 seconds:

```
5/3/2019, 5:38:30 PMnode: 2c6cfac2.f5e126
msg : string[52]
"failed to fetch session details from plex: undefined"
```
![image](https://user-images.githubusercontent.com/16184466/57171627-bb050300-6dca-11e9-9445-2a00d4354941.png)

Flow:
![image](https://user-images.githubusercontent.com/16184466/57171640-e1c33980-6dca-11e9-87df-0823b6c9438e.png)

```
[
    {
        "id": "2c6cfac2.f5e126",
        "type": "plex-ws-playing",
        "z": "43c31fcd.cd5e",
        "name": "",
        "server": "b75659f9.dd0898",
        "allowUpdates": false,
        "filters": [
            {
                "idx": 0,
                "key": "Player.title",
                "operator": "eq",
                "value": "SHIELD Downstairs",
                "valueType": "str"
            }
        ],
        "x": 160,
        "y": 800,
        "wires": [
            [
                "804a174e.850a28"
            ]
        ]
    },
    {
        "id": "804a174e.850a28",
        "type": "switch",
        "z": "43c31fcd.cd5e",
        "name": "",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "playing",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "paused",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "stopped",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "buffering",
                "vt": "str"
            }
        ],
        "checkall": "false",
        "repair": false,
        "outputs": 4,
        "x": 310,
        "y": 800,
        "wires": [
            [
                "42acd57c.e352cc"
            ],
            [
                "3e57a449.fbac1c"
            ],
            [
                "3e57a449.fbac1c"
            ],
            [
                "42acd57c.e352cc"
            ]
        ]
    },
    {
        "id": "42acd57c.e352cc",
        "type": "api-call-service",
        "z": "43c31fcd.cd5e",
        "name": "Plex Downstairs On",
        "server": "4000050f.bda52c",
        "service_domain": "input_boolean",
        "service": "turn_on",
        "data": "{\"entity_id\":\"input_boolean.plex_downstairs\"}",
        "mergecontext": "",
        "output_location": "",
        "output_location_type": "none",
        "x": 530,
        "y": 760,
        "wires": [
            []
        ]
    },
    {
        "id": "3e57a449.fbac1c",
        "type": "api-call-service",
        "z": "43c31fcd.cd5e",
        "name": "Plex Downstairs Off",
        "server": "4000050f.bda52c",
        "service_domain": "input_boolean",
        "service": "turn_off",
        "data": "{\"entity_id\":\"input_boolean.plex_downstairs\"}",
        "mergecontext": "",
        "output_location": "",
        "output_location_type": "none",
        "x": 530,
        "y": 820,
        "wires": [
            []
        ]
    },
    {
        "id": "b75659f9.dd0898",
        "type": "plex-ws-server",
        "z": "",
        "hostname": "plex.home.lab",
        "port": "32400",
        "timeout": "1000",
        "token": "TOKEN",
        "secure": false
    },
    {
        "id": "4000050f.bda52c",
        "type": "server",
        "z": "",
        "name": "Home Assistant",
        "legacy": false,
        "hassio": false,
        "rejectUnauthorizedCerts": false,
        "ha_boolean": "y|yes|true|on|home|open"
    }
]
```

**Comment by scraton** [comment]
Hi there!

I believe this happens with a newer version of Plex Media Server. Had it happen on my copy too. I pushed an update a couple days ago that should fix the issue for you too. Check for an upgrade in the plugin manager of Node RED and let me know if that works out for ya.

**Comment by causefx** [comment]
Hi again, I just updated the palette day before yesterday.  is there another update?

**Comment by scraton** [comment]
Hmm, no, version 0.2.1 is the latest. Sounds like it might be a different issue then.

Could you check your Node RED logs themselves (the logs from the server, not the web GUI)? That might give a hint at what’s going on.

**Comment by causefx** [comment]
The logs are just filled with this:

```
3 May 23:50:11 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:50:11 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:50:21 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:50:21 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:50:31 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:50:31 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:50:41 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:50:41 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:50:51 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:50:51 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:51:01 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:51:01 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:51:11 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:51:11 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:51:21 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:51:21 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:51:31 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:51:31 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:51:41 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:51:41 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:51:51 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
3 May 23:51:51 - [warn] [plex-ws-playing:2c6cfac2.f5e126] failed to fetch session details from plex: undefined
```

**Comment by cmille34** [comment]
Might be worth double checking your Plex token is correct. I just had the same exact issue. The node would say connected but not give any details about the stream. On a whim I followed the steps here again https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/ and sure enough it was using a different token than what it used to.

**Comment by blahbla** [comment]
I get this error every 5 days or so and need to delete the "app" from authorized devices in plex. Then I have to follow the steps to recreate and change the key.

**Comment by Klizzy** [comment]
i had the same issue since the last plex update. The token was correct, but i had to generate a new one like

**Comment by blahbla** [comment]
a restart of node-red makes the error go away for a while

**Comment by olvier** [comment]
Same here. Need to "update" the node, w/o changing anything. Just open, update, re-deploy.

Then it works for a while, but next time of watching a video, same error message
"failed to fetch session details from plex: undefined".

Also changed to a new key, same behaviour

Any sustainable solution?

**Comment by Hopperpop** [comment]
I added some debug code and it looks like the problems starts after the plexApi keeps returning empty mediacontainers. It looks like the code is braking after to many retries. I don't understand enough of javascript promises to fix the failing error handling, but I will look further if I can find the root cause of the empty containers.

```
Session fetched,
Session fetched,
Session fetched,
Session fetched,
start query,
statuscode: 200,
got sessions,
Response has mediacontainer, size:0,
{"size":0},
start query,
statuscode: 200,
got sessions,
Response has mediacontainer, size:0,
{"size":0},
start query,
statuscode: 200,
got sessions,
Response has mediacontainer, size:0,
{"size":0},
start query,
statuscode: 200,
got sessions,
Response has mediacontainer, size:0,
{"size":0},
start query,
statuscode: 200,
got sessions,
Response has mediacontainer, size:0,
{"size":0},
start query,
statuscode: 200,
got sessions,
Response has mediacontainer, size:0,
{"size":0},
start query,
statuscode: 200,
got sessions,
Response has mediacontainer, size:0,
{"size":0},
start query,
statuscode: 200,
got sessions,
Response has mediacontainer, size:0,
{"size":0},
start query,
statuscode: 200,
got sessions,
Response has mediacontainer, size:0,
{"size":0},
start query,
statuscode: 200,
got sessions,
Response has mediacontainer, size:0,
{"size":0},
start query,
statuscode: 200,
got sessions,
Response has mediacontainer, size:0,
{"size":0},
7 Dec 12:07:58 - [warn] [plex-ws-playing:d82cd089.1c808] failed to fetch session details from plex: undefined,
7 Dec 12:11:13 - [warn] [plex-ws-playing:d82cd089.1c808] failed to fetch session details from plex: undefined,
7 Dec 12:17:57 - [warn] [plex-ws-playing:d82cd089.1c808] failed to fetch session details from plex: undefined,
```

**Comment by causefx** [comment]
@scraton possible to get the PR merged?

**Comment by scraton** [comment]
Thanks for digging into this, y'all. I really appreciate it. And special thanks for @Hopperpop for providing a fix. I've merged and published a new version with the fix.

**Comment by causefx** [comment]
thanks @scraton and @Hopperpop i will update and test and provide feedback :)

**Comment by miguelpruivo** [comment]
This should be re-opened because I'm still experiencing this over and over, despite it working when plex is actually streaming something, but on idle, I get this.
